<?php



function immomemo_menu() {
    $items['test'] = array(
    	'page callback' => 'test',
  		'type' => MENU_CALLBACK,
  		'access callback' => 'immomemo_user_access',
    );
    $items['play'] = array(
    	'page callback' => 'play',
  		'type' => MENU_CALLBACK,
  		//'access callback' => 'immomemo_user_access',
  		'access callback' => true,
    );
    
    /*$items['ajax/walletMove'] = array(
    	'page callback' => 'walletMove',
  		'type' => MENU_CALLBACK,
  		'access callback' => 'immomemo_user_access',
    );*/
    return $items;
  }


function immomemo_user_access(){
	global $user;
	
	if($user->uid !== 0)
		return true;
	return false;
}

/**

Callback
*/

function test(){
	if ($test = false) {
		echo 'true';
		var_dump($test);
	}
	else{
		echo 'false';
		var_dump($test);
	}
}

function play(){
	global $user;
	//global $base_url;

	if($user->uid == 0){ // Not logged in
		//echo theme('immomemo_login');
		return theme('immomemo_login');
	}
	
	$CP = get_CP();
	require_once 'PHP/Mobile_Detect.php';
	$detect = new Mobile_Detect;


	if( $detect->isMobile() || $detect->isTablet()) {
 		echo theme('immomemo_mobile', array('CP'=>$CP));
	}
	else{
		//echo theme('immomemo_home', array('CP'=>$CP));  // PC ??
		echo theme('immomemo_mobile', array('CP'=>$CP)); // mobile
	}
}


/**

Themes
*/

function immomemo_theme($existing, $type, $theme, $path) {
	return array(
		'immomemo_home' => array(
			'template' => 'immomemo_templates/home',
			'arguments' => array(
				'CP' => array(),
				//'wallet' => array(),
			),
		),
		'immomemo_mobile' => array(
			'template' => 'immomemo_templates/mobilejquery',
			'arguments' => array(
				'CP' => array(),
				//'wallet' => array(),
			),
		),
		'immomemo_login' => array(
			'template' => 'immomemo_templates/login',
			'arguments' => array(
				//'CP' => array(),
				//'wallet' => array(),
			),
		),
	);
}

/**

Fonctions diverses
*/

